// Generated by CoffeeScript 1.11.1
module.exports = function(data) {
  var regex;
  regex = /\"name\"\:\"persistent_uuid\"\,\"value\"\:(\d+)/g;
  return data.replace(regex, '"name":"persistent_uuid","value":"\$1"');
};
