// Generated by CoffeeScript 1.11.1
exports.loadBatchInvoices = function(params, callback) {
  if (!(params && typeof params === 'object')) {
    throw new TSArgsError('teamsnap.loadBatchInvoices', 'must provide a query parameters');
  }
  return this.loadItems('batchInvoice', params, callback);
};

exports.createBatchInvoice = function(data) {
  return this.createItem(data, {
    type: 'batchInvoice'
  });
};

exports.saveBatchInvoice = function(batchInvoice, callback) {
  var ref;
  if (!batchInvoice) {
    throw new TSArgsError('teamsnap.saveBatchInvoice', "`batchInvoice` must be provided");
  }
  if (!this.isItem(batchInvoice, 'batchInvoice')) {
    throw new TSArgsError('teamsnap.saveBatchInvoice', "`batchInvoice.type` must be 'batchInvoice'");
  }
  if (!batchInvoice.divisionId) {
    return this.reject('You must provide a division.', 'divisionId', callback);
  }
  if (!((ref = batchInvoice.description) != null ? ref.trim() : void 0)) {
    return this.reject('You must provide a description for the batchInvoice.', 'description', callback);
  }
  return this.saveItem(batchInvoice, callback);
};

exports.deleteBatchInvoice = function(batchInvoice, callback) {
  if (!batchInvoice) {
    throw new TSArgsError('teamsnap.deleteBatchInvoice', '`batchInvoice` must be provided');
  }
  return this.deleteItem(batchInvoice, callback);
};
