// Generated by CoffeeScript 1.11.1
exports.loadCustomData = function(params, callback) {
  if (this.isId(params)) {
    params = {
      teamId: params
    };
  } else if (!(params && typeof params === 'object')) {
    throw new TSArgsError('teamsnap.loadCustomData', 'must provide a teamId or query parameters');
  }
  return this.loadItems('customDatum', params, callback);
};

exports.createCustomDatum = function(data, field) {
  return this.createItem(data, {
    type: 'customDatum',
    customFieldId: field.id,
    kind: field.kind,
    name: field.name,
    isPrivate: false,
    value: null
  });
};

exports.saveCustomDatum = function(customDatum, callback) {
  if (!customDatum) {
    throw new TSArgsError('teamsnap.saveCustomField', '`customDatum` must be provided');
  }
  if (!this.isItem(customDatum, 'customDatum')) {
    throw new TSArgsError('teamsnap.saveCustomField', "`customDatum.type` must be 'customDatum'");
  }
  return this.saveItem(customDatum, callback);
};
