// Generated by CoffeeScript 1.11.1
exports.PREFS = {
  SCHEDULE_SHOW: {
    ALL: 1,
    GAMES: 2,
    EVENTS: 3
  }
};

exports.loadDivisionMembersPreferences = function(params, callback) {
  if (this.isId(params)) {
    params = {
      teamId: params
    };
  } else if (!(params && typeof params === 'object')) {
    throw new TSArgsError('teamsnap.loadDivisionMembersPreferences', 'must provide a teamId or query parameters');
  }
  return this.loadItems('divisionMemberPreferences', params, callback);
};

exports.loadDivisionMemberPreferences = function(params, callback) {
  if (this.isId(params)) {
    params = {
      teamId: params
    };
  } else if (!(params && typeof params === 'object')) {
    throw new TSArgsError('teamsnap.loadDivisionMemberPreferences', 'must provide a teamId or query parameters');
  }
  return this.loadItem('divisionMemberPreferences', params, callback);
};

exports.saveDivisionMemberPreferences = function(divisionMemberPreferences, callback) {
  if (!divisionMemberPreferences) {
    throw new TSArgsError('teamsnap.saveDivisionMemberPreferences', "`divisionMemberPreferences` must be provided");
  }
  if (!this.isItem(divisionMemberPreferences, 'divisionMemberPreferences')) {
    throw new TSArgsError('teamsnap.saveDivisionMemberPreferences', "`divisionMemberPreferences.type` must be 'divisionMemberPreferences'");
  }
  return this.saveItem(divisionMemberPreferences, callback);
};
