// Generated by CoffeeScript 1.11.1
exports.loadDivisionTeamStandings = function(teamId, callback) {
  var params;
  if (!this.isId(teamId)) {
    throw new TSArgsError('teamsnap.loadDivisionTeamStandings', 'must provide a teamId');
  }
  params = {
    teamId: teamId
  };
  return this.loadItems('divisionTeamStanding', params, callback);
};
