// Generated by CoffeeScript 1.11.1
exports.loadDivisionAggregates = function(params, callback) {
  if (this.isId(params) || Array.isArray(params)) {
    params = {
      divisionId: params
    };
  } else if (!(params && typeof params === 'object')) {
    throw new TSArgsError('teamsnap.loadDivisionAggregates', 'must provide divisionId or query parameters');
  }
  return this.loadItems('divisionAggregate', params, callback);
};
