// Generated by CoffeeScript 1.11.1
exports.loadDivisionsPreferences = function(params, callback) {
  if (this.isId(params)) {
    params = {
      divisionId: params
    };
  } else if (!(params && typeof params === 'object')) {
    throw new TSArgsError('teamsnap.loadDivisionsPreferences', 'must provide a divisionId or query parameters');
  }
  return this.loadItems('divisionPreferences', params, callback);
};

exports.loadDivisionPreferences = function(params, callback) {
  if (this.isId(params)) {
    params = {
      divisionId: params
    };
  } else if (!(params && typeof params === 'object')) {
    throw new TSArgsError('teamsnap.loadDivisionPreferences', 'must provide a divisionId or query parameters');
  }
  return this.loadItem('divisionPreferences', params, callback);
};

exports.saveDivisionPreferences = function(divisionPreferences, callback) {
  if (!divisionPreferences) {
    throw new TSArgsError('teamsnap.saveDivisionPreferences', "`divisionPreferences` must be provided");
  }
  if (!this.isItem(divisionPreferences, 'divisionPreferences')) {
    throw new TSArgsError('teamsnap.saveDivisionPreferences', "`divisionPreferences.type` must be 'divisionPreferences'");
  }
  return this.saveItem(divisionPreferences, callback);
};
