// Generated by CoffeeScript 1.11.1
exports.loadDivisionStore = function(params, callback) {
  if (this.isId(params)) {
    params = {
      divisionId: params
    };
  } else if (!(params && typeof params === 'object')) {
    throw new TSArgsError('teamsnap.loadDivisionStore', 'must provide a divisionId or query parameters');
  }
  return this.loadItem('divisionStore', params, callback);
};
