// Generated by CoffeeScript 1.11.1
exports.loadEventStatistics = function(params, callback) {
  if (this.isId(params)) {
    params = {
      teamId: params
    };
  } else if (!(params && typeof params === 'object')) {
    throw new TSArgsError('teamsnap.loadEventStatistics', 'must provide a teamId or query parameters');
  }
  return this.loadItems('eventStatistic', params, callback);
};
