// Generated by CoffeeScript 1.11.1
exports.loadForumSubscriptions = function(params, callback) {
  if (this.isId(params)) {
    params = {
      teamId: params
    };
  } else if (!(params && typeof params === 'object')) {
    throw new TSArgsError('teamsnap.loadForumSubscriptions', 'must provide a teamId or query parameters');
  }
  return this.loadItems('forumSubscription', params, callback);
};

exports.createForumSubscription = function(data) {
  return this.createItem(data, {
    type: 'forumSubscription'
  });
};

exports.saveForumSubscription = function(forumSubscription, callback) {
  if (!forumSubscription) {
    throw new TSArgsError('teamsnap.saveForumSubscription', "`forumSubscription` must be provided");
  }
  if (!this.isItem(forumSubscription, 'forumSubscription')) {
    throw new TSArgsError('teamsnap.saveForumSubscription', "`type` must be 'forumSubscription'");
  }
  if (!forumSubscription.forumTopicId) {
    return this.reject('You must provide a forum topic id.', 'forumTopicId', callback);
  }
  if (!forumSubscription.memberId) {
    return this.reject('You must provide a member id.', 'memberId', callback);
  }
  return this.saveItem(forumSubscription, callback);
};

exports.deleteForumSubscription = function(forumSubscription, callback) {
  if (!forumSubscription) {
    throw new TSArgsError('teamsnap.deleteForumSubscription', '`forumSubscription` must be provided');
  }
  return this.deleteItem(forumSubscription, callback);
};
