// Generated by CoffeeScript 1.11.1
exports.loadForumPosts = function(params, callback) {
  if (this.isId(params)) {
    params = {
      teamId: params
    };
  } else if (!(params && typeof params === 'object')) {
    throw new TSArgsError('teamsnap.loadForumPosts', 'must provide a teamId or query parameters');
  }
  return this.loadItems('forumPost', params, callback);
};

exports.createForumPost = function(data) {
  return this.createItem(data, {
    type: 'forumPost'
  });
};

exports.saveForumPost = function(forumPost, callback) {
  var ref;
  if (!forumPost) {
    throw new TSArgsError('teamsnap.saveForumPost', "`forumPost` must be provided");
  }
  if (!this.isItem(forumPost, 'forumPost')) {
    throw new TSArgsError('teamsnap.saveForumPost', "`type` must be 'forumPost'");
  }
  if (!forumPost.forumTopicId) {
    return this.reject('You must provide a forum topic id.', 'forumTopicId', callback);
  }
  if (!forumPost.memberId) {
    return this.reject('You must provide a member id.', 'memberId', callback);
  }
  if (!((ref = forumPost.message) != null ? ref.trim() : void 0)) {
    return this.reject('You must provide a message for the forum post.', 'message', callback);
  }
  return this.saveItem(forumPost, callback);
};

exports.deleteForumPost = function(forumPost, callback) {
  if (!forumPost) {
    throw new TSArgsError('teamsnap.deleteForumPost', '`forumPost` must be provided');
  }
  return this.deleteItem(forumPost, callback);
};
