// Generated by CoffeeScript 1.11.1
exports.loadForumTopics = function(params, callback) {
  if (this.isId(params)) {
    params = {
      teamId: params
    };
  } else if (!(params && typeof params === 'object')) {
    throw new TSArgsError('teamsnap.loadForumTopics', 'must provide a teamId or query parameters');
  }
  return this.loadItems('forumTopic', params, callback);
};

exports.createForumTopic = function(data) {
  return this.createItem(data, {
    type: 'forumTopic'
  });
};

exports.saveForumTopic = function(forumTopic, callback) {
  var ref;
  if (!forumTopic) {
    throw new TSArgsError('teamsnap.saveForumTopic', "`forumTopic` must be provided");
  }
  if (!this.isItem(forumTopic, 'forumTopic')) {
    throw new TSArgsError('teamsnap.saveForumTopic', "`type` must be 'forumTopic'");
  }
  if (!forumTopic.teamId) {
    return this.reject('You must choose a team.', 'teamId', callback);
  }
  if (!((ref = forumTopic.title) != null ? ref.trim() : void 0)) {
    return this.reject('You must provide a title for the forum topic.', 'title', callback);
  }
  return this.saveItem(forumTopic, callback);
};

exports.deleteForumTopic = function(forumTopic, callback) {
  if (!forumTopic) {
    throw new TSArgsError('teamsnap.deleteForumTopic', '`forumTopic` must be provided');
  }
  return this.deleteItem(forumTopic, callback);
};
