// Generated by CoffeeScript 1.11.1
exports.loadInvoices = function(params, callback) {
  if (!(params && typeof params === 'object')) {
    throw new TSArgsError('teamsnap.loadInvoices', 'must provide query parameters');
  }
  return this.loadItems('invoice', params, callback);
};

exports.createInvoice = function(data) {
  return this.createItem(data, {
    type: 'invoice'
  });
};

exports.saveInvoice = function(invoice, callback) {
  if (!invoice) {
    throw new TSArgsError('teamsnap.saveInvoice', "`invoice` must be provided");
  }
  if (!this.isItem(invoice, 'invoice')) {
    throw new TSArgsError('teamsnap.saveInvoice', "`invoice.type` must be 'invoice'");
  }
  if (!invoice.batchInvoiceId) {
    return this.reject('You must choose a batchInvoiceId.', 'batchInvoiceId', callback);
  }
  if (!invoice.memberId) {
    return this.reject('You must choose a memberId.', 'memberId', callback);
  }
  return this.saveItem(invoice, callback);
};

exports.deleteInvoice = function(invoice, callback) {
  if (!invoice) {
    throw new TSArgsError('teamsnap.deleteInvoice', '`invoice` must be provided');
  }
  return this.deleteItem(invoice, callback);
};
