// Generated by CoffeeScript 1.11.1
exports.loadInvoiceLineItems = function(params, callback) {
  if (!(params && typeof params === 'object')) {
    throw new TSArgsError('teamsnap.loadInvoiceLineItems', 'must provide query parameters');
  }
  return this.loadItems('invoiceLineItem', params, callback);
};

exports.createInvoiceLineItem = function(data) {
  return this.createItem(data, {
    type: 'invoiceLineItem'
  });
};

exports.saveInvoiceLineItem = function(invoiceLineItem, callback) {
  if (!invoiceLineItem) {
    throw new TSArgsError('teamsnap.saveInvoiceLineItem', "`invoiceLineItem` must be provided");
  }
  if (!this.isItem(invoiceLineItem, 'invoiceLineItem')) {
    throw new TSArgsError('teamsnap.saveInvoiceLineItem', "`invoiceLineItem.type` must be 'invoiceLineItem'");
  }
  if (!invoiceLineItem.invoiceId) {
    return this.reject('You must choose an invoiceId.', 'invoiceId', callback);
  }
  if (!invoiceLineItem.quantity) {
    return this.reject('You must provide a quantity.', 'quantity', callback);
  }
  if (!invoiceLineItem.amount) {
    return this.reject('You must provide an amount.', 'amount', callback);
  }
  return this.saveItem(invoiceLineItem, callback);
};

exports.deleteInvoiceLineItem = function(invoiceLineItem, callback) {
  if (!invoiceLineItem) {
    throw new TSArgsError('teamsnap.deleteInvoiceLineItem', '`invoiceLineItem` must be provided');
  }
  return this.deleteItem(invoiceLineItem, callback);
};
