// Generated by CoffeeScript 1.11.1
exports.loadInvoiceTransactions = function(params, callback) {
  if (!(params && typeof params === 'object')) {
    throw new TSArgsError('teamsnap.loadInvoiceTransactions', 'must provide query parameters');
  }
  return this.loadItems('invoiceTransaction', params, callback);
};

exports.createInvoiceTransaction = function(data) {
  return this.createItem(data, {
    type: 'invoiceTransaction'
  });
};

exports.saveInvoiceTransaction = function(invoiceTransaction, callback) {
  if (!invoiceTransaction) {
    throw new TSArgsError('teamsnap.saveInvoiceTransaction', "`invoiceTransaction` must be provided");
  }
  if (!this.isItem(invoiceTransaction, 'invoiceTransaction')) {
    throw new TSArgsError('teamsnap.saveInvoiceTransaction', "`invoiceTransaction.type` must be 'invoiceTransaction'");
  }
  if (!invoiceTransaction.invoiceId) {
    return this.reject('You must provide an invoice.', 'invoiceId', callback);
  }
  if (!invoiceTransaction.kind) {
    return this.reject('You must provide a kind of invoice.', 'kind', callback);
  }
  if (!invoiceTransaction.amount) {
    return this.reject('You must provide an amount.', 'amount', callback);
  }
  return this.saveItem(invoiceTransaction, callback);
};
