// Generated by CoffeeScript 1.11.1
exports.loadLeagueCustomData = function(params, callback) {
  if (this.isId(params)) {
    params = {
      teamId: params
    };
  } else if (!(params && typeof params === 'object')) {
    throw new TSArgsError('teamsnap.loadLeagueCustomData', 'must provide a teamId or query parameters');
  }
  return this.loadItems('leagueCustomDatum', params, callback);
};

exports.createLeagueCustomDatum = function(data, field) {
  return this.createItem(data, {
    type: 'leagueCustomDatum',
    leagueCustomFieldId: field.id,
    kind: field.kind,
    name: field.name,
    isPrivate: false,
    value: null
  });
};

exports.saveLeagueCustomDatum = function(leagueCustomDatum, callback) {
  if (!leagueCustomDatum) {
    throw new TSArgsError('teamsnap.saveLeagueCustomDatum', '`leagueCustomDatum` must be provided');
  }
  if (!this.isItem(leagueCustomDatum, 'leagueCustomDatum')) {
    throw new TSArgsError('teamsnap.saveLeagueCustomDatum', "`leagueCustomDatum.type` must be 'leagueCustomDatum'");
  }
  return this.saveItem(leagueCustomDatum, callback);
};
