// Generated by CoffeeScript 1.11.1
exports.loadMemberPhotos = function(params, callback) {
  if (this.isId(params)) {
    params = {
      teamId: params
    };
  } else if (!(params && typeof params === 'object')) {
    throw new TSArgsError('teamsnap.loadMemberPhotos', 'must provide a `teamId` or query parameters');
  }
  return this.loadItems('memberPhoto', params, callback);
};

exports.loadMemberPhoto = function(params, callback) {
  if (this.isId(params)) {
    params = {
      id: params
    };
  } else if (!(params && typeof params === 'object')) {
    throw new TSArgsError('teamsnap.loadMemberPhoto', 'must provide an `id` or query parameters');
  }
  return this.loadItem('memberPhoto', params, callback);
};
