// Generated by CoffeeScript 1.11.1
exports.loadMemberAssignments = function(params, callback) {
  if (this.isId(params)) {
    params = {
      teamId: params
    };
  } else if (!(params && typeof params === 'object')) {
    throw new TSArgsError('teamsnap.loadMemberAssignments', 'must provide a teamId or query parameters');
  }
  return this.loadItems('memberAssignment', params, callback);
};

exports.createMemberAssignment = function(data) {
  return this.createItem(data, {
    type: 'memberAssignment'
  });
};

exports.saveMemberAssignment = function(memberAssignment, callback) {
  if (!memberAssignment) {
    throw new TSArgsError('teamsnap.saveMemberAssignment', "`memberAssignment` must be provided");
  }
  if (!this.isItem(memberAssignment, 'memberAssignment')) {
    throw new TSArgsError('teamsnap.saveMemberAssignment', "`memberAssignment.type` must be 'memberAssignment'");
  }
  return this.saveItem(memberAssignment, callback);
};

exports.deleteMemberAssignment = function(memberAssignment, callback) {
  if (!memberAssignment) {
    throw new TSArgsError('teamsnap.deleteMemberAssignment', '`memberAssignment` must be provided');
  }
  return this.deleteItem(memberAssignment, callback);
};
