// Generated by CoffeeScript 1.11.1
exports.loadOpponentsResults = function(params, callback) {
  if (!(params && typeof params === 'object')) {
    throw new TSArgsError('teamsnap.loadOpponentsResults', 'must provide query parameters');
  }
  return this.loadItems('opponentResults', params, callback);
};

exports.loadOpponentResults = function(opponentId, callback) {
  var params;
  if (!this.isId(opponentId)) {
    throw new TSArgsError('teamsnap.loadOpponentResults', 'must provide an opponentId');
  }
  params = {
    id: opponentId
  };
  return this.loadItem('opponentResults', params, callback);
};
