// Generated by CoffeeScript 1.11.1
exports.createPartnerUserPreferences = function(data) {
  return this.createItem(data, {
    type: 'partnerUserPreferences'
  });
};

exports.savePartnerUserPreferences = function(partnerUserPreferences, callback) {
  if (!partnerUserPreferences) {
    throw new TSArgsError('teamsnap.savePartnerUserPreferences', "`partnerUserPreferences` must be provided");
  }
  if (!this.isItem(partnerUserPreferences, 'partnerUserPreferences')) {
    throw new TSArgsError('teamsnap.savePartnerUserPreferences', "`partnerUserPreferences.type` must be 'partnerUserPreferences'");
  }
  if (!partnerUserPreferences.userId) {
    return this.reject('You must provide a user.', 'userId', callback);
  }
  if (!partnerUserPreferences.partnerPreferenceId) {
    return this.reject('You must provide a partnerPreference.', 'partnerPreferenceId', callback);
  }
  if (!partnerUserPreferences.optionValue.trim()) {
    return this.reject('You must provide an optionValue.', 'optionValue', callback);
  }
  return this.saveItem(partnerUserPreferences, callback);
};
