// Generated by CoffeeScript 1.11.1
exports.loadPartnersPreferences = function(params, callback) {
  if (!(params && typeof params === 'object')) {
    throw new TSArgsError('teamsnap.loadPartnersPreferences', 'must provide query parameters');
  }
  return this.loadItems('partnerPreferences', params, callback);
};
