// Generated by CoffeeScript 1.11.1
exports.loadPaymentNotes = function(params, callback) {
  if (this.isId(params)) {
    params = {
      teamId: params
    };
  } else if (!(params && typeof params === 'object')) {
    throw new TSArgsError('teamsnap.loadPaymentNotes', 'must provide a teamId or query parameters');
  }
  return this.loadItems('paymentNote', params, callback);
};

exports.createPaymentNote = function(data) {
  return this.createItem(data, {
    type: 'paymentNote'
  });
};

exports.savePaymentNote = function(paymentNote, callback) {
  if (!paymentNote) {
    throw new TSArgsError('teamsnap.savePaymentNote', '`paymentNote` must be provided');
  }
  if (!this.isItem(paymentNote, 'paymentNote')) {
    throw new TSArgsError('teamsnap.savePaymentNote', "`paymentNote.type` must be 'paymentNote'");
  }
  if (!paymentNote.teamId) {
    return this.reject('You must choose a team.', 'teamId', callback);
  }
  if (!paymentNote.memberPaymentId) {
    return this.reject('You must specify a memberPaymentId.', 'memberPaymentId', callback);
  }
  if (!paymentNote.note) {
    return this.reject('You must provide a note.', 'note', callback);
  }
  return this.saveItem(paymentNote, callback);
};
