// Generated by CoffeeScript 1.11.1
exports.loadRegistrationFormLineItems = function(params, callback) {
  if (!(params && typeof params === 'object')) {
    throw new TSArgsError('teamsnap.loadRegistrationFormLineItems', 'must provide query parameters');
  }
  return this.loadItems('registrationFormLineItem', params, callback);
};
