// Generated by CoffeeScript 1.11.1
exports.loadRegistrationFormLineItemOptions = function(params, callback) {
  if (!(params && typeof params === 'object')) {
    throw new TSArgsError('teamsnap.loadRegistrationFormLineItemOptions', 'must provide query parameters');
  }
  return this.loadItems('registrationFormLineItemOption', params, callback);
};
