// Generated by CoffeeScript 1.11.1
exports.loadRegistrationForms = function(params, callback) {
  if (this.isId(params)) {
    params = {
      id: params
    };
  } else if (!(params && typeof params === 'object')) {
    throw new TSArgsError('teamsnap.loadRegistrationForms', 'must provide a id or query parameters');
  }
  return this.loadItems('registrationForm', params, callback);
};
