// Generated by CoffeeScript 1.11.1
exports.loadStatisticData = function(params, callback) {
  if (this.isId(params)) {
    params = {
      teamId: params
    };
  } else if (!(params && typeof params === 'object')) {
    throw new TSArgsError('teamsnap.loadStatisticData', 'must provide a teamId or query parameters');
  }
  return this.loadItems('statisticDatum', params, callback);
};

exports.createStatisticDatum = function(data) {
  return this.createItem(data, {
    type: 'statisticDatum'
  });
};

exports.saveStatisticDatum = function(statisticDatum, callback) {
  if (!statisticDatum) {
    throw new TSArgsError('teamsnap.saveStatisticDatum', '`statisticDatum` must be provided');
  }
  if (!this.isItem(statisticDatum, 'statisticDatum')) {
    throw new TSArgsError('teamsnap.saveStatisticDatum', "`statisticDatum.type` must be 'statisticDatum'");
  }
  if (!statisticDatum.eventId) {
    return this.reject('You must specify an event.', 'eventId', callback);
  }
  if (!statisticDatum.statisticId) {
    return this.reject('You must specify a statistic.', 'statisticId', callback);
  }
  if (!statisticDatum.teamId) {
    return this.reject('You must choose a team.', 'teamId', callback);
  }
  return this.saveItem(statisticDatum, callback);
};

exports.deleteStatisticDatum = function(statisticDatum, callback) {
  if (!statisticDatum) {
    throw new TSArgsError('teamsnap.deleteStatisticDatum', '`statisticDatum` must be provided');
  }
  return this.deleteItem(statisticDatum, callback);
};

exports.bulkSaveStatisticData = function(templates, callback) {
  var params;
  if (!templates) {
    throw new TSArgsError('teamsnap.bulkSaveStatisticData', "`templates` must be provided");
  }
  params = {
    templates: templates
  };
  return this.collections.statisticData.exec('bulkUpdateStatisticData', params).callback(callback);
};

exports.bulkDeleteStatisticData = function(member, event, callback) {
  var params;
  if (!member) {
    throw new TSArgsError('teamsnap.bulkDeleteStatisticData', "`member` must be provided");
  }
  if (!this.isItem(member, 'member')) {
    throw new TSArgsError('teamsnap.bulkDeleteStatisticData', "`member.type` must be 'member'");
  }
  if (!event) {
    throw new TSArgsError('teamsnap.bulkDeleteStatisticData', "`event` must be provided");
  }
  if (!this.isItem(event, 'event')) {
    throw new TSArgsError('teamsnap.bulkDeleteStatisticData', "`event.type` must be 'event'");
  }
  params = {
    memberId: member.id,
    eventId: event.id
  };
  return this.collections.statisticData.exec('bulkDeleteStatisticData', params).callback(callback);
};
