// Generated by CoffeeScript 1.11.1
exports.loadTeamNames = function(params, callback) {
  if (this.isId(params)) {
    params = {
      id: params
    };
  } else if (!(params && typeof params === 'object')) {
    throw new TSArgsError('teamsnap.loadTeamNames', 'must provide a teamId or query parameters');
  }
  return this.loadItems('teamName', params, callback);
};
