// Generated by CoffeeScript 1.11.1
exports.loadTeamsPaypalPreferences = function(params, callback) {
  if (this.isId(params)) {
    params = {
      teamId: params
    };
  } else if (!(params && typeof params === 'object')) {
    throw new TSArgsError('teamsnap.loadTeamsPaypalPreferences', 'must provide a teamId or query parameters');
  }
  return this.loadItems('teamPaypalPreferences', params, callback);
};

exports.loadTeamPaypalPreferences = function(params, callback) {
  if (this.isId(params)) {
    params = {
      teamId: params
    };
  } else if (!(params && typeof params === 'object')) {
    throw new TSArgsError('teamsnap.loadTeamPaypalPreferences', 'must provide a teamId or query parameters');
  }
  return this.loadItem('teamPaypalPreferences', params, callback);
};

exports.saveTeamPaypalPreferences = function(teamPaypalPreferences, callback) {
  if (!teamPaypalPreferences) {
    throw new TSArgsError('teamsnap.saveTeamPaypalPreferences', "`teamPaypalPreferences` must be provided");
  }
  if (!this.isItem(teamPaypalPreferences, 'teamPaypalPreferences')) {
    throw new TSArgsError('teamsnap.saveTeamPaypalPreferences', "`teamPaypalPreferences.type` must be 'teamPaypalPreferences'");
  }
  return this.saveItem(teamPaypalPreferences, callback);
};
