// Generated by CoffeeScript 1.11.1
exports.loadTeamsResults = function(params, callback) {
  if (!(params && typeof params === 'object')) {
    throw new TSArgsError('teamsnap.loadTeamsResults', 'must provide query parameters');
  }
  return this.loadItems('teamResults', params, callback);
};

exports.loadTeamResults = function(teamId, callback) {
  var params;
  if (!this.isId(teamId)) {
    throw new TSArgsError('teamsnap.loadTeamResults', 'must provide a teamId');
  }
  params = {
    teamId: teamId
  };
  return this.loadItem('teamResults', params, callback);
};
