// Generated by CoffeeScript 1.11.1
exports.loadTeamMediumComments = function(params, callback) {
  if (this.isId(params)) {
    params = {
      teamId: params
    };
  } else if (!(params && typeof params === 'object')) {
    throw new TSArgsError('teamsnap.loadTeamMediumComments', 'must provide a teamId or query parameters');
  }
  return this.loadItems('teamMediumComment', params, callback);
};

exports.createTeamMediumComment = function(data) {
  return this.createItem(data, {
    type: 'teamMediumComment'
  });
};

exports.saveTeamMediumComment = function(teamMediumComment, callback) {
  if (!teamMediumComment) {
    throw new TSArgsError('teamsnap.saveTeamMediumComment', '`teamMediumComment` must be provided');
  }
  if (!this.isItem(teamMediumComment, 'teamMediumComment')) {
    throw new TSArgsError('teamsnap.saveTeamMediumComment', "`teamMediumComment.type` must be 'teamMediumComment'");
  }
  return this.saveItem(teamMediumComment, callback);
};

exports.deleteTeamMediumComment = function(teamMediumComment, callback) {
  if (!teamMediumComment) {
    throw new TSArgsError('teamsnap.deleteTeamMediumComment', '`teamMediumComment` must be provided');
  }
  return this.deleteItem(teamMediumComment, callback);
};
