// Generated by CoffeeScript 1.11.1
exports.loadTeamFees = function(params, callback) {
  if (this.isId(params)) {
    params = {
      teamId: params
    };
  } else if (!(params && typeof params === 'object')) {
    throw new TSArgsError('teamsnap.loadTeamFees', 'must provide a teamId or query parameters');
  }
  return this.loadItems('teamFee', params, callback);
};

exports.createTeamFee = function(data) {
  return this.createItem(data, {
    type: 'teamFee'
  });
};

exports.saveTeamFee = function(teamFee, callback) {
  if (!teamFee) {
    throw new TSArgsError('teamsnap.saveTeamFee', '`teamFee` must be provided');
  }
  if (!this.isItem(teamFee, 'teamFee')) {
    throw new TSArgsError('teamsnap.saveTeamFee', "`teamFee.type` must be 'teamFee'");
  }
  if (!teamFee.teamId) {
    return this.reject('You must choose a team.', 'teamId', callback);
  }
  if (!teamFee.description) {
    return this.reject('You must provide a team fee description.', 'description', callback);
  }
  if (!teamFee.amount) {
    return this.reject('You must provide a fee amount.', 'description', callback);
  }
  return this.saveItem(teamFee, callback);
};

exports.deleteTeamFee = function(teamFee, callback) {
  if (!teamFee) {
    throw new TSArgsError('teamsnap.deleteTeamFee', '`teamFee` must be provided');
  }
  return this.deleteItem(teamFee, callback);
};
