// Generated by CoffeeScript 1.11.1
exports.loadTeamPhotos = function(params, callback) {
  if (this.isId(params)) {
    params = {
      teamId: params
    };
  } else if (!(params && typeof params === 'object')) {
    throw new TSArgsError('teamsnap.loadTeamPhotos', 'must provide a `teamId` or query parameters');
  }
  return this.loadItems('teamPhoto', params, callback);
};

exports.loadTeamPhoto = function(params, callback) {
  if (this.isId(params)) {
    params = {
      id: params
    };
  } else if (!(params && typeof params === 'object')) {
    throw new TSArgsError('teamsnap.loadTeamPhoto', 'must provide an `id` or query parameters');
  }
  return this.loadItem('teamPhoto', params, callback);
};
